# $Id: makefile,v 1.1 2005/07/17 00:03:48 smilcke Exp $
TARGET		= test

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	test
SRCLAST	:=

include $(LXAPI32DEV)\makes\modmake.mak
