# $Id: makefile,v 1.6 2005/03/25 00:06:28 smilcke Exp $

TARGET		= lxdrvchar
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFITRST	:=
SRCFILES	:=ldbc_mem \
			ldbc_misc \
			ldbc_n_tty \
			ldbc_pty \
			ldbc_random \
			ldbc_tty_ioctl \
			ldbc_tty_io
SRCLAST 	:=

include $(LXAPI32DEV)\makes\libmake.mak
