# $Id: makefile,v 1.14 2006/02/16 23:07:21 smilcke Exp $

TARGET     = oxo

#==============================================================================
# Setup subdirectories
#==============================================================================
DIRS	:= drivers fs

#===================================================================
# List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	oo_fileio \
			oo_init \
			oo_irq \
			oo_misc \
			oo_miscw \
			oo_nonet \
			oo_os2fn \
			oo_process \
			oo_scrio \
			oo_script \
			oo_startchk \
			oo_symparm \
			oo_syscall \
			oo_thread \
			oo_todo \
			oo_trace

SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
