# $Id: makefile,v 1.4 2005/12/07 23:46:03 smilcke Exp $
TARGET		= modules

#===================================================================
# Setup subdirectories
#===================================================================
#DIRS	:= test
DIRS	:=

include $(LXAPI32DEV)\makes\modmake.mak
