# $Id: makefile,v 1.11 2005/03/25 00:06:26 smilcke Exp $

TARGET     = lxdrvbase
LXFORCEO   := 1

#==============================================================================
# Setup subdirectories
#==============================================================================
DIRS	:= power

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	ldb_bus \
			ldb_class_simple \
			ldb_class \
			ldb_core \
			ldb_cpu \
			ldb_dmapool \
			ldb_driver \
			ldb_firmware_class \
			ldb_firmware \
			ldb_init \
			ldb_interface \
			ldb_map \
			ldb_platform \
			ldb_sys
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
