# $Id: makefile,v 1.6 2005/02/06 22:49:22 smilcke Exp $

TARGET		= lxdrivers

#===================================================================
# Setup subdirectories
#===================================================================
DIRS	:= base char block

include $(LXAPI32DEV)\makes\libmake.mak
