# $Id: makefile,v 1.9 2005/05/20 22:20:32 smilcke Exp $

TARGET     = oxlib
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=ol_ioremap \
				ol_misc \
				ol_string
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
