# $Id: makefile,v 1.6 2005/03/25 00:06:31 smilcke Exp $

TARGET		= lxsecurity
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	ls_capability \
				ls_commoncap
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
