# $Id: makefile,v 1.3 2005/03/01 20:53:22 smilcke Exp $

TARGET		= lxdrivers

#===================================================================
# Setup subdirectories
#===================================================================
DIRS	:= block

include $(LXAPI32DEV)\makes\libmake.mak
