# $Id: makefile,v 1.2 2005/03/15 23:38:12 smilcke Exp $

TARGET     = oxdrvblock

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	odbl_ll_rw_blk
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
