# $Id: makefile,v 1.6 2005/07/25 20:04:23 smilcke Exp $

TARGET     = oxkernel

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	ok_exit \
			ok_fork \
			ok_module \
			ok_printk \
			ok_sched \
			ok_timer
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
