# $Id: makefile,v 1.6 2006/02/16 23:07:20 smilcke Exp $

TARGET     = oxinit
#LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	oi_main
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
