# $Id: makefile,v 1.9 2005/05/12 20:54:43 smilcke Exp $

TARGET     = lxarchlib
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=lal_dec_and_lock \
			lal_delay \
			lal_strstr
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
