# $Id: makefile,v 1.9 2005/12/26 23:42:02 smilcke Exp $

TARGET     = lxsysfs
LXFORCEO   := 1

HELLOMSG	= Building $(TARGET)

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	lfsf_bin \
			lfsf_dir \
			lfsf_file \
			lfsf_group \
			lfsf_inode \
			lfsf_mount \
			lfsf_symlink
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
