# $Id: makefile,v 1.2 2005/03/15 23:38:19 smilcke Exp $

TARGET     = oxofsppartitions

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	oofp_check \
			oofp_devfs \
			oofp_lx
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
