# $Id: makefile,v 1.2 2005/03/15 23:38:17 smilcke Exp $

TARGET     = oxodrivers

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	ood_lxdskdev
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
