# $Id: makefile,v 1.6 2005/03/25 00:06:24 smilcke Exp $

TARGET		= lxarchkcpu
LXFORCEO   := 1

#===================================================================
# Setup subdirectories
#===================================================================
DIRS	:= mcheck

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	lakc_centaur \
			lakc_common \
			lakc_cyrix \
			lakc_nexgen \
			lakc_proc \
			lakc_rise \
			lakc_transmeta \
			lakc_umc
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
