# $Id: makefile,v 1.6 2005/07/23 21:15:16 smilcke Exp $

TARGET     = oxarchlib
#LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	oal_getuser \
				oal_memcpy \
				oal_usercopy
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
