# $Id: makefile,v 1.14 2005/05/12 20:54:45 smilcke Exp $

TARGET     = lxlib
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	ll_bitmap \
			ll_bust_spinlocks \
			ll_cmdline \
			ll_ctype \
			ll_extable \
			ll_idr \
			ll_kobject \
			ll_mmap \
			ll_parser \
			ll_radix-tree \
			ll_rbtree \
			ll_rwsem \
			ll_semaphore \
			ll_videodev \
			ll_vsprintf \
			ll_waitq
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
