# $Id: makefile,v 1.4 2005/03/15 23:38:12 smilcke Exp $

TARGET     = oxarchmm

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	oam_init \
			oam_pgtable
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
