# $Id: makefile,v 1.4 2005/03/25 00:06:24 smilcke Exp $

TARGET     = lxarchkcmcheck
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	lakcm_k7 \
				lakcm_mce \
				lakcm_non-fatal \
				lakcm_p4 \
				lakcm_p5 \
				lakcm_p6 \
				lakcm_winchip
SRCLAST 	:=

include $(LXAPI32DEV)\makes\libmake.mak

