# $Id: makefile,v 1.6 2005/05/06 22:04:04 smilcke Exp $

TARGET		= oxofs

#===================================================================
# Setup subdirectories
#===================================================================
DIRS	:= lxafs partitions

#===================================================================
# List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	oof_binfmt_lxexe

SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
