# $Id: makefile,v 1.6 2006/02/16 23:07:18 smilcke Exp $

TARGET     = lxinit
#LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	li_do_mounts \
			li_initramfs \
			li_version
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
