# $Id: makefile,v 1.6 2005/03/15 23:38:19 smilcke Exp $

TARGET     = oxofslxa

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	oofl_dentry \
			oofl_dir \
			oofl_file \
			oofl_inode \
			oofl_io \
			oofl_misc \
			oofl_name
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
