# $Id: makefile,v 1.8 2005/02/06 22:49:20 smilcke Exp $

TARGET		= lxarch

#===================================================================
# Setup subdirectories
#===================================================================
DIRS	:= kernel lib mach-default

include $(LXAPI32DEV)\makes\libmake.mak
