# $Id: makefile,v 1.4 2005/02/06 22:49:28 smilcke Exp $

TARGET		= os2

#===================================================================
# Setup subdirectories
#===================================================================
DIRS	:= arch drivers fs init kernel lib mm os2

include $(LXAPI32DEV)\makes\libmake.mak
