_init_text SEGMENT DWORD PUBLIC USE32 'CODE'
_init_text ENDS
_sched_text SEGMENT DWORD PUBLIC USE32 'CODE'
_sched_text ENDS
_exit_text SEGMENT DWORD PUBLIC USE32 'CODE'
_exit_text ENDS
_init_data SEGMENT DWORD PUBLIC USE32 '_init_data'
_init_data ENDS
_init_setup SEGMENT DWORD PUBLIC USE32 '_init_setup'
_init_setup ENDS
_initcall1_init SEGMENT DWORD PUBLIC USE32 '_initcall1_init'
_initcall1_init ENDS
_initcall2_init SEGMENT DWORD PUBLIC USE32 '_initcall2_init'
_initcall2_init ENDS
_initcall3_init SEGMENT DWORD PUBLIC USE32 '_initcall3_init'
_initcall3_init ENDS
_initcall4_init SEGMENT DWORD PUBLIC USE32 '_initcall4_init'
_initcall4_init ENDS
_initcall5_init SEGMENT DWORD PUBLIC USE32 '_initcall5_init'
_initcall5_init ENDS
_initcall6_init SEGMENT DWORD PUBLIC USE32 '_initcall6_init'
_initcall6_init ENDS
_initcall7_init SEGMENT DWORD PUBLIC USE32 '_initcall7_init'
_initcall7_init ENDS
_exitcall_exit SEGMENT DWORD PUBLIC USE32 '_exitcall_exit'
_exitcall_exit ENDS
__ksymtab_strings SEGMENT DWORD PUBLIC USE32 'CONST'
__ksymtab_strings ENDS
__ksymtab SEGMENT DWORD PUBLIC USE32 'CONST'
__ksymtab ENDS
__ksymtab_gpl SEGMENT DWORD PUBLIC USE32 'CONST'
__ksymtab_gpl ENDS
