# $Id: makefile,v 1.5 2005/03/25 00:06:29 smilcke Exp $

TARGET     = lxramfs
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=lfr_inode
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
