# $Id: makefile,v 1.5 2005/04/04 22:39:58 smilcke Exp $

TARGET		= lxlibc

#===================================================================
# Setup subdirectories
#===================================================================
DIRS	:= crt0 libc

include $(LXAPI32DEV)\makes\libcmake.mak
