# $Id: makefile,v 1.5 2005/05/20 22:20:30 smilcke Exp $

TARGET     = oxfs

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
# of_binfmt_aout
SRCFILES	:=	of_binfmt_script \
			of_buffer \
			of_exec
SRCLAST		:=

EMXOMFAROPTS	:= -p32

include $(LXAPI32DEV)\makes\libmake.mak
