# $Id: makefile,v 1.1 2005/07/11 22:18:33 smilcke Exp $

TARGET		= lxmodule

#===================================================================
# Setup subdirectories
#===================================================================
DIRS	:= insmod

include $(LXAPI32DEV)\makes\libmake.mak
