# $Id: makefile,v 1.4 2005/07/11 22:18:32 smilcke Exp $

TARGET		= lxutils

#===================================================================
# Setup subdirectories
#===================================================================
DIRS	:= init module

include $(LXAPI32DEV)\makes\libmake.mak
