# $Id: makefile,v 1.7 2005/02/14 00:22:31 smilcke Exp $

TARGET		= os2arch

#===================================================================
# Setup subdirectories
#===================================================================
DIRS	:= kernel lib mm

include $(LXAPI32DEV)\makes\libmake.mak
