# $Id: makefile,v 1.5 2005/03/25 00:06:25 smilcke Exp $

TARGET		= lxarchmdefault
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=lamd_setup \
			lamd_topology
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
