# $Id: makefile,v 1.3 2005/05/20 22:20:30 smilcke Exp $

TARGET     = oxarchkcpu
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	oakc_amd \
			oakc_intel
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
