# $Id: makefile,v 1.9 2005/03/25 00:06:30 smilcke Exp $

TARGET     = lxmm
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	lm_mempool
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
