/* $Id: Config.cmd,v 1.7 2005/03/01 20:53:20 smilcke Exp $ */

/*
 * Configuration script.
 * Generates global makefile.inc.
 *
 * Copyright (c) 1999-2000 knut st. osmundsen (knut.stange.osmundsen@pmsc.no)
 * Modified for BT-Drivers 2002 Stefan Milcke
 *
*/

Call RxFuncAdd 'SysLoadFuncs', 'RexxUtil', 'SysLoadFuncs';
Call SysLoadFuncs;

Parse Arg sIncFile
if (sIncFile='') Then sIncFile='paths.mak'

Say 'Current directory:'directory()
Say 'Generating 'directory()'\'sIncFile

/* Status */
Say 'Configuring the LXAPI32 driver...'

/* delete old file */
Call SysFileDelete sIncFile

/* open target file */
If (Stream(sIncFile, 'C', 'OPEN WRITE' ) <> '') Then
Do
 Call LineOut sIncFile, '################################################################################'
 Call LineOut sIncFile, '# Generated by 'directory()'\config.cmd'
 Call LineOut sIncFile, '################################################################################'
 Call LineOut sIncFile, ''
 sBase=directory();
 sLast=Translate(sBase,' ','\')
 sLast=Word(sLast,Words(sLast))
 Call LineOut sIncFile, 'DRV_BASE	:='sBase
 Call LineOut sIncFile, 'LX_BASE 	:=$(LXAPI32DEV)'
 Call LineOut sIncFile, 'ifdef LXAPIROOT'
 Call LineOut sIncFile, ' LX_ROOT	:=$(LXAPIROOT)'
 Call LineOut sIncFile, 'else'
 Call LineOut sIncFile, ' LX_ROOT	:=$(LXAPI32DEV)\root'
 Call LineOut sIncFile, 'endif'
 Call LineOut sIncFile,	'ifndef OBJ_BASE'
 Call LineOut sIncFile, ' OBJ_BASE	:='sBase'\..\BIN\'sLast
 Call LineOut sIncFile, 'endif'

 Call directory(sOldDir);
 Say ''
 Say 'Configuration completed!'
End
Else
Do
 Say 'oops, failed to open outputfile,' sIncFile;
 Exit 1;
End
Exit 0;
