# $Id: makefile,v 1.9 2005/02/06 22:49:19 smilcke Exp $

TARGET		= LINUX
LXLINUXDEBUG	= 1
export LXLINUXDEBUG

#===================================================================
# Setup subdirectories
#===================================================================
DIRS	:= arch drivers fs init kernel lib mm security usr

include $(LXAPI32DEV)\makes\libmake.mak
