# $Id: makefile,v 1.6 2005/03/25 00:06:26 smilcke Exp $

TARGET     = lxdrvblock
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=ldbl_as-iosched \
			ldbl_deadline-iosched \
			ldbl_elevator \
			ldbl_genhd \
			ldbl_ioctl \
			ldbl_noop-iosched \
			ldbl_scsi_ioctl
SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
