# $Id: makefile,v 1.7 2005/03/25 00:06:25 smilcke Exp $

TARGET		= lxarchktimers
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=	lakt_timer_none \
				lakt_timer_pit \
				lakt_timer_tsc \
				lakt_timer
SRCLAST :=

include $(LXAPI32DEV)\makes\libmake.mak
