# $Id: makefile,v 1.5 2005/03/25 00:06:26 smilcke Exp $

TARGET     = lxdrvbpower
LXFORCEO   := 1

#===================================================================
#   List of source files
#===================================================================
SRCFIRST	:=
SRCFILES	:=ldbp_main \
			ldbp_resume \
			ldbp_runtime \
			ldbp_shutdown \
			ldbp_suspend \
			ldbp_sysfs

SRCLAST		:=

include $(LXAPI32DEV)\makes\libmake.mak
